site_name: Catálogo D&D
site_url: https://logoff.github.io/catalogo-dnd/
site_dir: ./dist/
docs_dir: ./src/

theme:
  name: material
  palette:
    scheme: slate
  language: es
  logo: img/dungeons-and-dragons-black.png
  favicon: img/dungeons-and-dragons.png
  features:
    - navigation.instant # Instant loading: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
    - navigation.tracking # Anchor tracking: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-tracking
    - navigation.tabs
    - navigation.tabs.sticky ## Sticky navigation tabs: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-tracking
    - navigation.top # Back-to-top button
    - toc.integrate # Navigation integration: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-integration

plugins:
  - search
  - glightbox:
      touchNavigation: true
  - roamlinks
  - awesome-pages
  - macros:
      on_error_fail: true
      verbose: true

markdown_extensions:
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/d-and-d
      link: https://dnd.wizards.com/es
      name: Dungeons & Dragons
    - icon: fontawesome/brands/github
      link: https://github.com/logoff/catalogo-dnd
      name: GitHub - Catálogo D&D

copyright: Copyright &copy; 2023 logoff
