[tool.poetry]
name = "catalogo-dnd"
version = "0.1.0"
description = "Catálogo de productos de Dungeons & Dragons 5ª edición"
authors = ["logoff"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mkdocs = "^1.4.3"
mkdocs-material = "^9.1.16"
mkdocs-roamlinks-plugin = "^0.3.2"
mkdocs-awesome-pages-plugin = "^2.9.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
