name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build and publish site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install just
        uses: extractions/setup-just@v3
      - name: Build & publish site
        run: |
          just publish-site
